# Generated by Django 3.2.9 on 2021-11-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Business', 'Business'), ('IT', 'IT'), ('Literature', 'Literature')], max_length=10)),
            ],
        ),
    ]
