# Generated by Django 3.2.9 on 2021-11-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Business', 'Business'), ('IT', 'IT'), ('Literature', 'Literature')], default='IT', max_length=10),
        ),
    ]
