# Generated by Django 3.2.3 on 2021-12-10 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211210_1747'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
